name: barangay-dashboard-env
channels:
  - defaults
dependencies:
  - python=3.9
  - flask
  - flask-cors
  - gunicorn
  - pytest
  - flake8
  - pip  # Make sure pip itself is listed as a Conda dependency
  - pip:
    - google-generativeai as genai # Tell Conda to install this package using pip
